# Generated by Django 5.1.7 on 2025-03-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_ticket_price_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
